# Production profile configuration
spring:
  # Database configuration
  datasource:
    url: jdbc:mysql://mysql:3306/permission_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: PermissionHikariCP
  
  # JPA configuration
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  
  # Redis configuration
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 10s
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 5

# Logging configuration
logging:
  level:
    root: warn
    com.example.permission: info
  file:
    name: /var/logs/permission-system/application.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# Spring Doc (Swagger) configuration
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false