# Development profile configuration
spring:
  # Database configuration
  datasource:
    url: jdbc:mysql://47.100.231.51:3306/feemgmt?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: feemgmt
    password: Dan7844$$
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: PoolHikariCP
  
  # JPA configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  
  # Redis configuration
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10s
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
#  sql:
#    init:
#      platform: mysql
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql
#      encoding: UTF-8
#      enabled: true

# Logging configuration
logging:
  level:
    root: info
    com.example.permission: debug
    org.springframework.web: info
    org.springframework.security: info
    org.hibernate.SQL: debug

# Spring Doc (Swagger) configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true